bt2_index: "/work/mc394/GenomeIndex/bowtie2/GRCm38"
blacklist: "reference_data/mm10.blacklist.bed"
countfile: "peaks/generic.counts"
annotation: "/work/mc394/genomes/annotation/wgencode.vM17.primary_assembly.annotation.gtf"
paired: "false"