bt2_index: "/work/mc394/index/bowtie2/mm10"
blacklist: "reference_data/mm10.blacklist.bed"
countfile: "peaks/SX_atac_idr.counts"
annotation: "/work/mc394/genomes/annotation/gencode.vM22.annotation.gtf"
paired: "true"
samples:
  naive: 
    - naive_01
    - naive_03
  9hr_CXCL2neg:
    - 9hr_CXCL2neg_01
    - 9hr_CXCL2neg_03
  9hr_CXCL2pos:
    - 9hr_CXCL2pos_01
    - 9hr_CXCL2pos_03
  24hr_CXCL2neg:
    - 24hr_CXCL2neg_01
    - 24hr_CXCL2neg_03
  24hr_CXCL2neg:
    - 24hr_CXCL2pos_01
    - 24hr_CXCL2pos_03